### ISSUE TITLE
Custom script name has to be defined in the page_config.py 

### ISSUE THREAD

**Issue by avrabyt** [blackary/mpa-config#6]
If I'm not wrong, incase of custom script names , it has to be defined as well as in the `page_config.py` . 
For example, `streamlit_app.py`  is defined explicitly in the `page_config.py`  [here](https://github.com/blackary/mpa-config/blob/afe9eb2ab0d6177141dd5edff1be949cfa2f88d2/page_config.py#L32) .

Just wondering, if it would be OK to add that in the [Readme section ](https://github.com/blackary/mpa-config#get-started). 

Thank you for this! Great work btw, Congratulations 🎉

**Comment by blackary** [comment]
Hi @avrabyt! The only reason I added `streamlit_app.py` to that page_config.py was so that you could do this: 

```yml
- page_name: Streamlit App
  icon: 🏠
```

Normally, if you don't pass a custom script, it will assume it's in `pages`, so it would assume this one was `pages/streamlit_app.py`. 

If you always define a `script_path`, this doesn't matter. But, I wanted you to be able to do:

```yml
- page_name: Example One
  icon: 🤠
```
And have it automatically know that it should look in `pages/example_one.py`

**Comment by avrabyt** [comment]
Ah I see, thanks ☺️
